[theme]
base = "light"
primaryColor = "#4F6BED"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F5FB"
textColor = "#1F2328"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
